### ISSUE TITLE
Unable to pull this library into project - Unauthorized

### ISSUE THREAD

**Issue by ruairimcguigan** [chRyNaN/inject#1]
**Describe the bug**
When integrating with my project (and a clean standalone project) - I get this error

Could not GET 'https://maven.pkg.github.com/chrynan/inject/com/chrynan/inject/inject-jvm/0.7.0/inject-jvm-0.7.0.pom'. Received status code 401 from server: Unauthorized

**To Reproduce**
Steps to reproduce the behaviour:
1. Add maven repo to top level build.gradle
2. Add library dependency to app build.gradle 
3. Sync and rebuild
4. See error: 
Could not GET 'https://maven.pkg.github.com/chrynan/inject/com/chrynan/inject/inject-jvm/0.7.0/inject-jvm-0.7.0.pom'. Received status code 401 from server: Unauthorized

**Expected behaviour**
Dep should be available in project

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Comment by chRyNaN** [comment]
Hi @ruairimcguigan thanks for reporting this issue. Could you provide your repository and dependency definitions? For example:
```kotlin
repositories {
    maven {
        url = uri("https://dl.bintray.com/chrynan/chrynan")
    }
}

dependencies {
    implementation("com.chrynan.inject:inject-jvm:0.7.0")
}
```

Also, you should be able to drop the platform specific target and just use the default one which should get resolved properly:
```kotlin
implementation("com.chrynan.inject:inject-common:0.7.0")
```

**Comment by chRyNaN** [comment]
The issue seems to be that you are trying to download from the Github Packages Repository. Instead you should download from the Bintray Maven Repository. Add the following repository to the `repositories` block in your `build.gradle` file:
```kotlin
repositories {
    maven {
        url = uri("https://dl.bintray.com/chrynan/chrynan")
    }
}
```

Please let me know if that solves your issue so that I can close this issue.
